version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_Test_0906Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_test_0906.integrations:AddInt
  packages:
  - name: SIQA_GIT_Test_0906Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
