version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_Test_0906Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: DADA_GlobalVariable1
  version: "1.0"
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SIQACloudStreamsTests
  version: "1.0"
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_git_test_0906.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_GIT_Test_0906Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqa_git_test_0906.integrations:AddInt
  packages:
  - name: SIQA_GIT_Test_0906Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.siqa_git_test_0906.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GIT_Test_0906Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqa_git_test_0906.integrations:TPP_Service
  packages:
  - name: SIQA_GIT_Test_0906Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: GB_1:readGlobalvariable
  packages:
  - name: DADA_GlobalVariable1
    version: "1.0"
- serviceName: pub.globalVariable:getGlobalVariable
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
